name: Web E2E tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node version
        run: node --version

      - name: Instalando dependÃªncias
        run: npm install

      - name: Executando testes
        run: npx cypress run